### ISSUE TITLE
202_換気扇掃除

### ISSUE THREAD

**Issue by yunoda-3DCG** [EngineMaker/eM_Narita#19]

**Comment by yunoda-3DCG** [comment]
汚れがひどすぎるので、本体ごと取り換えることにしました。
https://www.amazon.co.jp/dp/B001TVETCO?smid=AN1VRQENFRJN5&ref_=chk_typ_imgToDp&th=1

**Comment by timeserver** [comment]
めちゃ感謝。
機械的には動くから、なんかの機会に清掃して、どこかで使ってみたい気持ちが少し
